apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ws1
  name: ws1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ws1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: ws1
    spec:
      containers:
      - env:
        - name: APPID
          value: "1111"
        image: chatterona-websocket-api
        imagePullPolicy: ""
        name: ws1
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
